version: 0.2

phases:
  #install:
  #  runtime-versions:
  #    docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      #- $(aws ecr-public get-login --no-include-email --region us-east-1)
      - $(aws ecr-public get-login-password --region us-east-1)
      - REPOSITORY_URI=public.ecr.aws/t9t2v5b8/app_image_repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
